src/forensic/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

from . import views


app_name = "forensic"
urlpatterns = [
    path("", RedirectView.as_view(pattern_name="forensic:instructions")),
    path("instructions/", include([
        path("", views.InstructionList.as_view(), name="instructions"),
        path(
            "with-too-many-hair-samples/",
            views.too_many_hair_samples,
            name="too_many_hair_samples",
        ),
        path("<int:pk>/", include([
            path(
                "",
                views.InstructionDetail.as_view(),
                name="instruction_detail",
            ),
        ])),
    ])),
    path("collections/", include([
        path("", RedirectView.as_view(pattern_name="forensic:instructions")),
        path(
            "<int:pk>/",
            views.CollectionDetail.as_view(),
            name="collection_detail",
        ),
    ])),
    path("samples/", include([
        path("", RedirectView.as_view(pattern_name="forensic:instructions")),
        path(
            "<int:pk>/",
            views.SampleDetail.as_view(),
            name="sample_detail",
        ),
    ])),
]

src/forensic/models.py
from django.db import models
from django.urls import reverse


class Instruction(models.Model):
    client_name = models.CharField(max_length=255)

    def __str__(self):
        return f"instruction for {self.client_name}"

    def get_absolute_url(self):
        return reverse("forensic:instruction_detail", kwargs={"pk": self.pk})

    def hair_sample_count(self):
        count = 0
        for collection in self.collection_set.all():
            for sample in collection.sample_set.all():
                if sample.sample_type == sample.SampleType.HAIR:
                    count += 1

        return count


class Collection(models.Model):
    instruction = models.ForeignKey(
        "forensic.Instruction",
        on_delete=models.CASCADE,
    )

    when = models.DateTimeField()
    postcode = models.CharField(max_length=8)

    def __str__(self):
        return f"collection at {self.postcode}"

    def get_absolute_url(self):
        return reverse("forensic:collection_detail", kwargs={"pk": self.pk})


class Sample(models.Model):
    collection = models.ForeignKey(
        "forensic.Collection",
        on_delete=models.CASCADE,
    )

    class SampleType(models.TextChoices):
        HAIR = "hair", "Hair"
        BLOOD = "blood", "Blood"

    sample_type = models.CharField(max_length=5, choices=SampleType)

    def __str__(self):
        return f"{self.sample_type} sample"

    def get_absolute_url(self):
        return reverse("forensic:sample_detail", kwargs={"pk": self.pk})

src/forensic/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import Collection, Instruction, Sample


class InstructionList(ListView):
    model = Instruction


class InstructionDetail(DetailView):
    model = Instruction


class CollectionDetail(DetailView):
    model = Collection


class SampleDetail(DetailView):
    model = Sample


def too_many_hair_samples(request):
    instructions = []
    for instruction in Instruction.objects.all():
        if instruction.hair_sample_count() > 70:
            instructions.append(instruction)

    return render(
        request,
        "forensic/instruction_list.html",
        {
            "object_list": instructions,
            "too_many_hair_samples_view": True,
        },
    )

src/forensic/templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}Forensic LIMS{% endblock %}</title>

  {# https://bootswatch.com/4/solar/ #}
  <link
    rel="stylesheet"
    href="https://bootswatch.com/4/solar/bootstrap.css"
  />
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Forensic LIMS</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarColor01"
      aria-controls="navbarColor01"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <section class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'forensic:instructions' %}">
            Instructions List
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'forensic:too_many_hair_samples' %}">
            Problematic Instructions
          </a>
        </li>
      </ul>
    </section>
  </nav>
  {% block content %}{% endblock %}

  {% block js %}{% endblock %}
</body>
</html>

src/forensic/templates/forensic/collection_detail.html
{% extends "base.html" %}

{% block content %}
  <article class="container">
    <ul class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{{ object.instruction.get_absolute_url }}">
          Instruction
        </a>
      </li>
      <li class="breadcrumb-item active">Sample</li>
    </ul>

    <h1>{{ object|capfirst }}</h1>

    <h2>Samples</h2>

    <section class="row">
      <ul>
        {% for sample in object.sample_set.all %}
          <li>
            <a href="{% url 'forensic:sample_detail' sample.pk %}">
              {{ sample }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  </article>
{% endblock %}

src/forensic/templates/forensic/instruction_detail.html
{% extends "base.html" %}

{% block content %}
  <article class="container">
    <ul class="breadcrumb">
      <li class="breadcrumb-item active">Instruction</li>
    </ul>

    <h1>{{ object|title }}</h1>

    <section class="row">
      <p>
        This instruction has {{ object.hair_sample_count }} hair samples.
      </p>
    </section>

    <h2>Collections</h2>

    <section class="row">
      <ul>
        {% for collection in object.collection_set.all %}
          <li>
            <a href="{% url 'forensic:collection_detail' collection.pk %}">
              {{ collection|capfirst }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  </article>
{% endblock %}

src/forensic/templates/forensic/instruction_list.html
{% extends "base.html" %}

{% block content %}
  <article class="container">
    <h1>Instructions</h1>

    <section class="row">
      {% if too_many_hair_samples_view %}
        <p>
          This page shows any instructions which have too many hair
          samples, so that the lab to prepare for them.
        </p>
      {% endif %}
    </section>

    <section class="row">
      <ul>
        {% for instruction in object_list %}
          <li>
            <a href="{{ instruction.get_absolute_url }}">
              {{ instruction|title }}
            </a>
            with {{ instruction.hair_sample_count }} hair samples.
          </li>
        {% endfor %}
      </ul>
    </section>
  </article>
{% endblock %}

src/forensic/templates/forensic/sample_detail.html
{% extends "base.html" %}

{% block content %}
  <article class="container">
    <ul class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{{ object.collection.instruction.get_absolute_url }}">
          Instruction
        </a>
      </li>
      <li class="breadcrumb-item">
        <a href="{{ object.collection.get_absolute_url }}">
          Collection
        </a>
      </li>
      <li class="breadcrumb-item active">Sample</li>
    </ul>

    <h1>{{ object|title }}</h1>
  </article>
{% endblock %}